### ISSUE TITLE
error: Matrix inversion failed!

### ISSUE THREAD

**Issue by aseetharam** [johnlees/seer#41] opened 2016-10-03 17:03 UTC
Sorry, didn't knew if I should re-open the previous issue or create a new issue. 
https://github.com/johnlees/seer/issues/37
Since the error message is different, I posted it as a new issue. I tried running `seer` command with the binary phenotype file. Although it runs fine for the single kmer/few kmers as suggested in the previous issue, it fails on a larger file:
Command I ran:
```for f in {00..15}; do seer -k fsm_out${f}.gz -p metadata_binary.pheno  --struct projection --threads 16 --maf 0.05 > seer${f}.txt; done```

Output:
```
A matrix inversion failed!
A matrix inversion failed!
A matrix inversion failed!
...
...
```
Interestingly, `seer${f}.txt` also had entries:
```
head seer00.txt
sequence        maf     unadj_p_val     p_val   beta    se      covar1_p        covar2_p        covar3_p        comments
TTTTTTTTT       1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTT      1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTTT     1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTTTT    1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTTTTT   1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTTTTTT  1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTTTTTTT 1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTTTTTTTT        1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
TTTTTTTTTTTTTTTTT       1.000   nan     0.000e+00       0.000e+00       0.000e+00       bad-chisq,inv-fail
```

**Comment by johnlees** [comment] 2016-10-04 08:49
I think the problem is that with 12 samples (see the caveats in my previous comment), you'll need a minor allele frequency cutoff of at least --maf 0.25 (or you can use the minor allele count option).

Even then I think many of the chi-squared tests will fail ('bad-chisq'). Perhaps in your case a frequency comparison of k-mers between groups would be more appropriate, though SEER does not currently implement this.

**Comment by johnlees** [comment] 2016-10-17 11:01
Closing, as I think issue is too few samples to fit the model

**Closed by johnlees** 2016-10-17 11:01 UTC
