### ISSUE TITLE
A matrix inversion failed!

### ISSUE THREAD

**Issue by RobertWeberRKI** [johnlees/seer#31] opened 2016-04-19 14:24 UTC
Hi all, 

i tried to run SEER and received the following error: 

1. fsm-lite -v -s 5 -S 95 -l fsm_list.txt -t tmp_index > fsm_kmers.txt
2. gzip fsm_kmers.txt
3. kmds -k fsm_kmers.txt.gz -p metadata.pheno --no_filtering --no_mds --size 10000
4. kmds -k fsm_kmers.txt.dsm -p metadata.pheno -o all_structure --threads 120 --write distances
5. $ seer -k all_structures.kmers.gz -p metadata.pheno --struct all_structure.dsm >significant_kmers.txt 

seer: sequence element enrichment analysis
Detected binary phenotype
A matrix inversion failed!
A matrix inversion failed! 
Done.

Furthermore the all-structuredistances.csv does not contain values but 0.000000...+00

How can I fix this problem?

**Comment by johnlees** [comment] 2016-04-19 14:30
Try running, instead of steps 3 and 4:
kmds -k fsm_kmers.txt.gz -p metadata.pheno --no_filtering --size 200000 -o all_structure --threads 120 --write_distances
and see if the all_structure.distances.csv file is correct

If you still get the problem, run a minimal example of 3:
kmds -k fsm_kmers.txt.gz -p metadata.pheno --no_filtering --no_mds --size 1000
and attach the output file fsm_kmers.txt.dsm to this thread

**Comment by RobertWeberRKI** [comment] 2016-04-20 08:30
I tried both options but nothing changed. 

> kmds -k fsm_kmers.txt.gz -p metadata.pheno --no_filtering --size 200000 -o all_structure --threads 120 --write_distances

Unfortunately .csv does not contain specific values 

> kmds -k fsm_kmers.txt.gz -p metadata.pheno --no_filtering --no_mds --size 1000

see attached file 
[fsm_kmers.txt.zip](https://github.com/johnlees/seer/files/227496/fsm_kmers.txt.zip)

**Comment by johnlees** [comment] 2016-04-25 09:39
Sorry for the delayed response. When I look at your fsm_kmers.dsm file using 'h5dump' it appears all the 10 000 k-mers subsampled are not present in any of 99 samples, which creates a matrix of zeros.

The most likely cause is mismatched names between your .pheno file and the fsm_kmers.txt.gz file. Could you check whether they match?

If you think they do could you attach your .pheno file and first 100 lines of fsm_kmers.txt.gz here (please feel free to permute the labels of your pheno file, if you don't wish to share your metadata).

**Comment by RobertWeberRKI** [comment] 2016-05-02 08:32
No problem. It seems like that the isolates in .txt.gz and .pheno file perfectly match. Metadata of attached .pheno file are modified. Thank you for your efforts!
[metadata2.zip](https://github.com/johnlees/seer/files/244713/metadata2.zip)
[fsm_list.zip](https://github.com/johnlees/seer/files/244714/fsm_list.zip)

**Comment by RobertWeberRKI** [comment] 2016-05-02 09:18
No problem at all! The names in fsm_kmers.txt.gz are generated out of .fsm_list.txt right? The names between .pheno file and fsm_list.txt do match perfectly. The names in fsm_kmers.txt.gz also seem to match with .pheno file. I've attached modified .pheno file and first 100 lines of fsm_kmers.txt.gz
[metadata2.zip](https://github.com/johnlees/seer/files/244777/metadata2.zip)
[fsm_kmers_100.zip](https://github.com/johnlees/seer/files/244779/fsm_kmers_100.zip)

**Comment by johnlees** [comment] 2016-05-04 11:10
I think the problem is the first two columns in the pheno file must be identical, in this case you should change the second column to match the first as specified [here](https://github.com/johnlees/seer/wiki/Usage#pheno-file). Sorry that this may be unclear, it's a hangover from the [plink](https://www.cog-genomics.org/plink2/input#pheno) format. There are also two tabs between the second column and the third.

I've attached an example of your pheno file that works here. I'll close the issue, but please go ahead and reopen it if your problem isn't solved.
[reformatted_metadata2.zip](https://github.com/johnlees/seer/files/248626/reformatted_metadata2.zip)

**Closed by johnlees** 2016-05-04 11:10 UTC

**Comment by RobertWeberRKI** [comment] 2016-05-09 07:37
Great, it worked! However, i do not get any values or results in the significant_kmers.txt. 

I tried to run: 

> kmds -k fsm_kmers.txt -p metadata.pheno --no_filtering --size 200000 -o all_structure --threads 120 --write_distances

followed by: 

> seer -k fsm_kmers.txt.gz -p metadata.pheno --struct all_structure.dsm --threads 4 --print_samples > significant_kmers.txt 

I would be very pleased to hear from you!

**Comment by johnlees** [comment] 2016-05-09 09:34
Try running the seer step with the options

    --pval 1 --chisq 1

**Comment by RobertWeberRKI** [comment] 2016-05-27 07:56
The tool worked! However, I've got an issue regarding specific significant k-mers after the mapping-proccess (see attached file). It would be great to hear from you! 
[SEER.pdf](https://github.com/johnlees/seer/files/285980/SEER.pdf)

**Comment by johnlees** [comment] 2016-05-31 11:06
Hi Robert,

In answer to your questions:
1. Have you filtered the k-mers by the direction of effect? If the non-mutated k-mers have a negative beta this is the expected result, and will actually improve your power to detect an effect in this region (in this case a depletion rather than enrichment of the k-mer)
2. The number of samples available and the fact that there are no controls with the mutation means that a logistic regression will not do a good job of estimating the p-value here. The 'bad-chisq' in the comment field suggests you should look carefully at this k-mer. You can see that for both this k-mer and the one above they show a large effect size (|beta|), but this one has a high standard error suggesting a bad fit. Both the p-values and effect sizes are informative
3. A p-value of 7.8e-04 may be expected under the null (check a q-q plot). Alternatively, we have found that sometimes phage sequence can be in linkage with causal hits independent of background population structure (meaning they are false positives). Whether or not a mutation is found may be arbitrary, as it depends entirely on the reference you have mapped to.

**Comment by RobertWeberRKI** [comment] 2016-05-31 13:22
Hello John, 

I've now performed the filtering process. However, all kmers with mutations (which are significant in PLINK analysis) exhibt a negative beta (depletion of kmers) while those without mutation seem to be enriched in this region. That do not make any sense to me. Maybe you have an idea?

**Comment by johnlees** [comment] 2016-05-31 13:31
Is this consistent with how you have encoded the phenotype i.e. are cases 0 or 1?

**Comment by RobertWeberRKI** [comment] 2016-05-31 13:36
cases are 0 and controls are 1 as described here: 

> The third field is the phenotype. Entirely 0/1 will be interpreted as binary case/control, anything else as quantitative.

**Comment by johnlees** [comment] 2016-05-31 14:26
Ah, I have written that the wrong way round! That would explain it then, if you code them the other way round then the effect directions will be as they should, and I think all your results are consistent with what's expected. (Rather than rerunning everything just flipping the sign of the beta column would be equivalent)

My interpretation of your results would be that the SNP you see causes the phenotype. The k-mers in the phage probably just co-occur in the same lineage as your non-resistant samples, but this may be worth investigating further if you think it might be interesting.

Apologies for the documentation of the pheno file, I've now fixed that!

**Comment by mgalardini** [comment] 2016-06-06 09:00
Hi John,

I also several 'A matrix inversion failed!' error when running seer; from what I can see from the results, this happens when the kmer is present in almost all samples with no phenotypes and almost all the samples with the phenotype. For example the kmer is present in 328 "no phenotype" samples over 329 and in 18 "phenotype" samples out of 20.

Is that something to worry about?

**Comment by johnlees** [comment] 2016-06-07 11:48
@mgalardini This is to be expected - this k-mer has a frequency of 99% in the population so these tests won't work well here. I set the default --maf parameter to 0.01 based on 3000 samples. You might consider raising it to 0.05, or setting --min_words to at least 10 to avoid this issue

I have now also added line numbers to these error messages in 0638f1d which I hope can help diagnose these issues

**Comment by mgalardini** [comment] 2016-06-08 08:31
Thank you John, I was just worried that those errors were a sign that something was wrong with the data.
One last question (sorry!): does it matter how we encode the phenotype? I'm setting 1 to susceptible strains and 0 to resistant; I guess that then I should look for high frequencies instead of low ones?

Thank you very much

**Comment by johnlees** [comment] 2016-06-08 09:24
@mgalardini That's fine - you'll just expect those k-mers with **negative** beta values to be the ones positively associated with resistance

**Comment by mgalardini** [comment] 2016-06-08 09:55
That's very clear, thank you very much

**Comment by RobertWeberRKI** [comment] 2016-07-22 09:11
Hello John, 
I've got a problem. After the mapping approach I've found kmers with 3 mutations and a coverage of about 15. In the results file, isolates are listet harbouring these kmers. I started from the assumption, that all 3 snps are present in those isolates. However, if I do map the orignial protein back to the assemblies it shows that not all isolates do carry all 3 mutations.  Have you a clue how this problem arises? 
I've attached a file to visualize the issue. 
[Problem_SEER.pdf](https://github.com/johnlees/seer/files/377858/Problem_SEER.pdf)

**Comment by johnlees** [comment] 2016-07-29 08:33
Could be misassembly of the protein, could be mismapping of the kmers. Do these kmers map to other places in the genome?

You should be able to get an exact match for them (the significant kmers with the three variants) if you map them to the assemblies they are from - check this is in the protein you're looking at.
